### ISSUE TITLE
很激动能发现你的项目，有几个问题想了解下，希望帮忙解答

### ISSUE THREAD

**Issue by zhengxiaochuan-3** [0-u-0/dugon-media-server#3]
1、看到你有计划使用 pion/webrtc 来重写 media-server ，但 pion 的性能我有点担心，mediasoup 的底层是基于 google webrtc lib 的 c++ 实现，应该对性能更有保障？
2、比如天南海北共100个人，参加同一个会议，我在东南西北四个机房各部署多个 dugon-media-server 和 dugon-signal-server 实例，用户接入时，我按地域来调度到对应区域的 server。那么对于一个"房间/会议"，该房间的信令和媒体能力都是跨域的多个 server 共同提供的吧？分布式？ 
3、 欢迎 pr 共同开发吗？

十分感谢！

**Comment by craterone** [comment]
1. 这个我还在调研， 的确会有性能问题。而且pion有很多我不需要的功能，这个我还没定，不一定用pion，这个是长期计划。
2. 可以跨区域，区域之间的通信主要通过 NATS 实现。调度逻辑我没加，准备通过ip库判断区域实现。
3. 当然可以。 我最近入职新公司，近段时间应该没空搞这个。


On June 30, 2020 at 6:20:37 PM, Jim Raynor (notifications@github.com) wrote:

1、看到你有计划使用 pion/webrtc 来重写 media-server ，但 pion 的性能我有点大担心，mediasoup 的底层是基于
google webrtc lib 的 c++ 实现，应该对性能更有保障？
2、比如天南海北共100个人，参加同一个会议，我在东南西北四个机房各部署多个 dugon-media-server 和
dugon-signal-server 实例，按地域来调度到对应区域的 server。那么对于一个"房间/会议"，该房间的信令和媒体能力都是跨域的多个
server 共同提供的吧？分布式？
3、 欢迎 pr 共同开发吗？

十分感谢！

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/0-u-0/dugon-media-server/issues/3>, or unsubscribe

**Comment by zhengxiaochuan-3** [comment]
2. 可以跨区域，区域之间的通信主要通过 NATS 实现。调度逻辑我没加，准备通过ip库判断区域实现。
//  我理解控制、信令是走 NATS ，媒体流应该是用 mediasoup transport 实现？

**Comment by craterone** [comment]
流媒体走的 mediasoup pipetransport，目前只支持 one hop。


On June 30, 2020 at 6:36:29 PM, Jim Raynor (notifications@github.com) wrote:


   1. 可以跨区域，区域之间的通信主要通过 NATS 实现。调度逻辑我没加，准备通过ip库判断区域实现。
   // 我理解控制、信令是走 NATS ，媒体流应该是用 mediasoup transport 实现？

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/0-u-0/dugon-media-server/issues/3#issuecomment-651681390>,
or unsubscribe
